[build]
buildCommand = "npm install --no-audit --no-fund && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
